/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc2981 from "./erc2981";
export type { erc2981 };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { FanficToken } from "./FanficToken";
export type { Market } from "./Market";
export type { MteToken } from "./MteToken";
export type { OriginToken } from "./OriginToken";
export type { Protocol } from "./Protocol";
export type { StakingToken } from "./StakingToken";
