/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as mock from "./mock";
export { ERC2981MultipleRoyalties__factory } from "./ERC2981MultipleRoyalties__factory";
export { IERC2981MultipleRoyalties__factory } from "./IERC2981MultipleRoyalties__factory";
