/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mock from "./mock";
export type { mock };
export type { ERC2981MultipleRoyalties } from "./ERC2981MultipleRoyalties";
export type { IERC2981MultipleRoyalties } from "./IERC2981MultipleRoyalties";
