/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IFanficToken } from "./IFanficToken";
export type { IMarket } from "./IMarket";
export type { IMteToken } from "./IMteToken";
export type { IOriginToken } from "./IOriginToken";
export type { IProtocol } from "./IProtocol";
export type { IStakingToken } from "./IStakingToken";
