/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IFanficToken__factory } from "./IFanficToken__factory";
export { IMarket__factory } from "./IMarket__factory";
export { IMteToken__factory } from "./IMteToken__factory";
export { IOriginToken__factory } from "./IOriginToken__factory";
export { IProtocol__factory } from "./IProtocol__factory";
export { IStakingToken__factory } from "./IStakingToken__factory";
