/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IOriginToken,
  IOriginTokenInterface,
} from "../../../contracts/interfaces/IOriginToken";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "tokenURI",
        type: "string",
      },
    ],
    name: "mint",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "protocol",
        type: "address",
      },
    ],
    name: "setProtocol",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "totalSupply",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IOriginToken__factory {
  static readonly abi = _abi;
  static createInterface(): IOriginTokenInterface {
    return new utils.Interface(_abi) as IOriginTokenInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IOriginToken {
    return new Contract(address, _abi, signerOrProvider) as IOriginToken;
  }
}
